ackermann_mux:
  ros__parameters:
    topics:
      joy:
        topic   : joy_teleop/ackermann_cmd
        timeout : 0.5
        priority: 10
      bt_joy:
        topic   : bluetooth_teleop/ackermann_cmd
        timeout : 0.5
        priority: 9
      interactive_marker:
        topic   : twist_marker_server/ackermann_cmd
        timeout : 0.5
        priority: 8
      external:
        topic   : ackermann_cmd
        timeout : 0.5
        priority: 1
    locks:
      e_stop:
        topic   : e_stop
        timeout : 0.0
        priority: 255